name: FlyClasses
main: ru.flydev.kartograf.FlyClasses
version: 0.0.1

commands:
   basic:
      description: This is a demo command.
      usage: /frpg
      permission: flyclasses.frpg
      permission-message: You don't have permission.